baseURL = 'https://f3soil.com/'
languageCode = 'en-us'
title = 'F3 SOIL'
theme = 'spectral'
publishDir = 'docs'

[params]
fancyTitle = 'F3 SOIL'
description = '<p>F3 Workouts are:</p><p>1. Free of Charge</p><p>2. Open to All Men</p><p>3. Held Outdoors</p><p>4. Peer Led</p><p>5. Ends in a Circle of Trust</p>'
body_is_markdown = true
custom_css_files = ['css/custom.css']
fineprint = '''
The circle F3 logo is used with the permission of <a href="https://f3nation.com/">F3 Nation</a> and is a registered trademark of F3 Nation, Inc.
'''

[[params.menu.main]]
url = '/locations/'
title = "Overview"

[[params.menu.main]]
url = '/locations/nomad/'
title = "Nomad (O'Fallon)"

[[params.menu.main]]
url = '/locations/outer-rim/'
title = "The Outer Rim (Fairview Heights)"

[[params.menu.main]]
url = '/locations/station/'
title = "The Station (O'Fallon)"

[[params.menu.main]]
url = '/locations/stomping-grounds/'
title = "The Stomping Grounds (Belleville)"

[[params.menu.main]]
url = '/locations/absoluschon/'
title = "Absoluschon (Glen Carbon)"

[[params.menu.main]]
url = '/locations/iron-horse/'
title = "The Iron Horse (St. Jacob)"

[[params.menu.main]]
url = '/locations/mine/'
title = "The Mine (Maryville)"

[[params.menu.main]]
url = '/locations/smokestack/'
title = "The Smokestack (Collinsville)"

[[params.menu.main]]
url = '/locations/store/'
title = "The Store (Edwardsville)"

[[params.menu.main]]
url = '/locations/zoo/'
title = "The Zoo (Troy)"

[params.one]
enable = true
title = 'What is F3? What is F3 SOIL?'
body = '''
F3 SOIL is the (SO)uthern (IL)linois and St. Louis Metro East region of [F3](https://f3nation.com/).
The mission of F3 is to plant, grow, and serve small workout groups for men for the invigoration of male community leadership.

Fitness: This is why we initially show up. We want to get in better shape and we find that this is more rewarding in a group. Iron sharpens iron.

Fellowship: A cup of coffee is surprisingly refreshing after a workout and even more so is the chatter.

Faith: F3 is not a religious organization but men are best when they are part of something bigger than themselves so we encourage service to your faith, family, friends, and community.

'''

[params.two]
enable = true

[[params.two.section]]
# https://www.zeemaps.com/map?group=4619598
img = "img/ao_map.png"
title = 'Where are the workouts held?'
body = '''
Our locations are listed under the Locations menu in the upper-right.
Reach out (below) or just show up.
We rarely cancel a scheduled workout so it's almost guaranteed we'll be there.
'''

[[params.two.section]]
img = "img/img_5555.png"
title = 'What should I bring to a workout?'
body = '''
You should dress appropriate for the weather.
If it's cold out be sure to layer so you can peel a layer off if you get too hot.
Working gloves (leather, heavy-duty latex, etc.) are a good idea.
We'll typically gift you a 35 lb cinderblock to use for weighted exercises.
'''

[[params.two.section]]
img = "img/img_5459.jpg"
title = 'What sort of exercises will I be doing?'
body = '''
We do standard body-weight exercises such as push-ups, jumping jacks, and squats.
We also make use of a 35 lb cinderblock to do exercises such as overhead presses, kettlebell swings, and curls.
'''

[[params.two.section]]
img = "img/img_5324.jpg"
title = 'How intense will the workout be?'
body = '''
We always say, "push yourself, don't hurt yourself."
We encourage all participants to modify as needed, up or down, so that they get an invigorating and safe workout.

The credo fo F3 is, "Leave no man behind, but leave no man where you find him."
We strive to ensure no man is left working alone so regularly "pickup the six" by contributing reps, joining in on reps, or holding a static hold in support.
'''

[params.three]
enable = true
title = 'F3 Gateway Super Region'
body = '''
F3 SOIL is part of the F3 Gateway Super Region if you have friends or family or work on the Missouri-side of the river you can checkout these other regions for additional locations.
F3 may be found all over the United States, and even the world, so if you're traveling and want to stay in your routine you may find there is a location near you; see [F3 Nation](https://f3nation.com/) for additional locations.
'''

[[params.three.feature]]
title = "F3 Ironplains"
body = '''
F3 Ironplains Starfished off of our region on May 10, 2025.
See <a href="https://www.f3ironplains.com/">F3 Ironplains</a> for more info.
'''

[[params.three.feature]]
title = "F3 St. Louis"
body = '''
See <a href="https://f3stlouis.com/">F3 St. Louis</a> for more info.
'''

[[params.three.feature]]
title = "F3 SoCo"
body = '''
See <a href="https://www.facebook.com/profile.php?id=61552638899167">F3 SoCo</a> for more info.
'''

[[params.three.feature]]
title = "F3 NoCo"
body = '''
See <a href="https://www.facebook.com/profile.php?id=100095183142148">F3 NoCo</a> for more info.
'''

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = ""
address = ""
email = "f3soil@googlegroups.com"
subject = "F3 SOIL New Contact"
formspree_form_id = "myyazorb"

[params.social]
twitter = "F3_SOIL"
facebook = "F3SOIL"

[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.f3]
languageName = "F3"
weight = 2

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
